### ISSUE TITLE
生成されたGifが自動的に消えません

### ISSUE THREAD

**Issue by urasakikeisuke** [nakajima-john-shotaro/AIcon#1]
https://github.com/nakajima-john-shotaro/AIcon/blob/55dacb8e4295d06f96e0e0001eaedd6b3bd213a6/shared_dir/AIcon/backend/src/main.py#L116
https://github.com/nakajima-john-shotaro/AIcon/blob/55dacb8e4295d06f96e0e0001eaedd6b3bd213a6/shared_dir/AIcon/backend/src/main.py#L118
https://github.com/nakajima-john-shotaro/AIcon/blob/55dacb8e4295d06f96e0e0001eaedd6b3bd213a6/shared_dir/AIcon/backend/src/main.py#L120

このあたりが怪しいと思うのですが...

**Comment by nakajima-john-shotaro** [comment]
修正しました。

**Comment by urasakikeisuke** [comment]
素早い対応ありがとうございました。
