### ISSUE TITLE
今後の予定

### ISSUE THREAD

**Issue by urasakikeisuke** [nakajima-john-shotaro/AIcon#2]
いつも素晴らしいプログラムありがとうございます。

突然ですが、今後新たなソフトを開発されたりするご予定などありますでしょうか。
またAIconに新たな機能追加するなどのご予定はございますでしょうか。

よろしくおねがいします。

**Comment by nakajima-john-shotaro** [comment]
質問ありがとうございます。
今後は、アイコンの生成速度を向上しようと考えています。
また、UIとUXの改良も検討しています。

**Comment by urasakikeisuke** [comment]
返信ありがとうございます。
楽しみに待っています。
